### ISSUE TITLE
Time out error, mounted volue

### ISSUE THREAD

**Issue by tugot17** [qdrant/qdrant-client#108]
**System**
Windows 11

**The problem**
Once I mount the volume to `qdrant/storage` from time to time I get `time out` error for `recreate_collection` function. The error occures randomly, and independently of whether I set the `timeout` parameter to `None` or `30`. 

The error occurs from time to time, but not always. Interestingly, the error occurs much faster than after the 30 seconds I pass as a parameter. Furthermore, the collection is initialized, and I can add new entries to it, even if I get a timeout error while creating it (in a previous run of the script). 

**Code**
```py
from qdrant_client import QdrantClient
from qdrant_client.http.models import Distance, VectorPara

client = QdrantClient(host="localhost", port=6333)

name = "my_collection"

client.recreate_collection(
    collection_name=name,
    vectors_config=VectorParams(size=3, distance=Distance.COSINE),
    timeout=None
)
```

```yaml
version: "3.9"
services:
  qdrant:
    image: qdrant/qdrant:v0.11.7
    ports:
      - "6333:6333"
      - "6334:6334"
    restart: always
    volumes:
      - ./qdrant_storage:/qdrant/storage
````
