### ISSUE TITLE
Qdrant Batch Upsert Speed

### ISSUE THREAD

**Issue by totalhack** [qdrant/qdrant-client#143]
I'm using batch upserts during initialization to ensure that qdrant has all relevant embeddings stored. In my testing I am surprised the upsert is not faster, but maybe this is just expected performance. I'm doing a batch upsert of a little more than 100 vectors with small payloads and it is taking about 2.5s on average on my local machine. A more traditional database would be able to bulk insert 100 rows probably in 10s of milliseconds, which is what my expectations are based on (perhaps incorrectly).

I'm using python 3.9, running the ~latest qdrant locally via docker, on a mid 2022 laptop.  

The vectors are OpenAI embeddings which have large dimensionality...perhaps that slows things down for some reason? I'm guessing there is something I don't understand about what qdrant needs to do under the hood but 2.5s to bulk insert 100ish rows seems quite slow.

**Comment by kacperlukawski** [comment]
@totalhack Hi, could you please share some details on the connection? Do you use HTTP or gRPC protocol? What are the parameters of the machine Qdrant is running?

**Comment by totalhack** [comment]
The qdrant server is running with the default docker settings. My docker compose:

```yaml
version: "3.8"
services:    
  qdrant:
    image: qdrant/qdrant
    ports:
      - 6333:6333
      - 6334:6334
    environment:
      - TZ=America/New_York
    volumes:
      - ./volumes/qdrant:/qdrant/storage
```

The python code is using the rest model.

```python
from qdrant_client.http import models as rest

# ...later in code

client = QdrantClient(host=host, port=6333)
client.upsert(
    collection_name=collection_name,
    points=rest.Batch(ids=ids, vectors=vectors, payloads=payloads),
)
```

Anything else I can provide?
